### ISSUE TITLE
Add our simple artifactory script

### ISSUE THREAD

**Issue by buep** [Praqma/code-utils#3]

**Comment by buep** [comment]
@praqmaTim can you share your recent Artifactory up/download script in this public repository?

You can send it to me if that is easier, then I will make it anonymous and dump it here.
Also welcome to remove customer details yourself and just add it here.

**Comment by praqmaTim** [comment]
It is on a branch in the DSV DevOps repo in github.

**Comment by Andrey9kin** [comment]
Guys, have you seen this one https://www.jfrog.com/blog/artifactory-command-line-interface-cli-pure-and-simple/

**Comment by buep** [comment]
Thanks @Andrey9kin - haven't seen that before. I will mention it in the readme. The script is done long time ago... nothing new, so I just share it anyway.

**Comment by buep** [comment]
@praqmaTim I deleted the repository yesterday, do you have a local clone or copy of the script? Didn't check if there was unmerged branches.

**Comment by buep** [comment]
Tim will post me latest today or during the weekend.

**Comment by buep** [comment]
I'm taking this issue out of the milestone, and back on the backlog. I don't want it to block the release.

**Comment by praqmaTim** [comment]
I have added the scripts. Sorry for the delay. But was busy.

**Comment by praqmaTim** [comment]
Added Artifactory Handler section to top level readme.
